/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/catalog/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog Skills */
        get: operations["catalog_skills_api_catalog_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog Voices */
        get: operations["catalog_voices_api_catalog_voices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog Providers */
        get: operations["catalog_providers_api_catalog_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog Models */
        get: operations["catalog_models_api_catalog_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Channels */
        get: operations["list_channels_api_channels_get"];
        put?: never;
        /** Create Channel */
        post: operations["create_channel_api_channels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Channel */
        get: operations["get_channel_api_channels__name__get"];
        /** Update Channel */
        put: operations["update_channel_api_channels__name__put"];
        post?: never;
        /** Delete Channel */
        delete: operations["delete_channel_api_channels__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Character */
        post: operations["upload_character_api_characters_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Library */
        get: operations["library_api_characters_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /** Launch */
        post: operations["launch_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gallery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gallery */
        get: operations["gallery_api_gallery_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_character_api_characters_upload_post */
        Body_upload_character_api_characters_upload_post: {
            /** File */
            file: string;
        };
        /**
         * Channel
         * @description Un channel = un type de vidéo à produire (unité éditable du panneau).
         */
        Channel: {
            /** Name */
            name: string;
            /** Skill */
            skill: string;
            models: components["schemas"]["ModelPool"];
            context?: components["schemas"]["Context"];
        };
        /**
         * Character
         * @description Personnage nommé (miroir éditable de CharacterConfig). Tous champs optionnels.
         */
        Character: {
            /** Image */
            image?: string | null;
            /** Voice */
            voice?: string | null;
            /** Style */
            style?: string | null;
            /** Voice Model */
            voice_model?: string | null;
            /** Language */
            language?: string | null;
            /** Description */
            description?: string | null;
        };
        /** CharacterAsset */
        CharacterAsset: {
            /** Name */
            name: string;
            /** Blob */
            blob: string;
            /** Url */
            url: string;
        };
        /**
         * Context
         * @description Brief créatif du channel.
         */
        Context: {
            /**
             * Prompt
             * @default
             */
            prompt: string;
            ressources?: components["schemas"]["Ressources"];
            /**
             * Mood
             * @default
             */
            mood: string;
            /** Characters */
            characters?: {
                [key: string]: components["schemas"]["Character"];
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ModelPool
         * @description Pool de modèles par rôle (le cœur d'un `models_config`).
         */
        ModelPool: {
            master_mind: components["schemas"]["ModelSpec"];
            slm: components["schemas"]["ModelSpec"];
            lip_sync: components["schemas"]["ModelSpec"];
            video_generator: components["schemas"]["ModelSpec"];
            voice_generator: components["schemas"]["ModelSpec"];
        };
        /**
         * ModelSpec
         * @description Un modèle pour un rôle : le nom + une RÉFÉRENCE de provider (pas de token).
         */
        ModelSpec: {
            /** Model Name */
            model_name: string;
            /** Provider Id */
            provider_id: string;
        };
        /** ModelSpecOut */
        ModelSpecOut: {
            /** Model Name */
            model_name: string;
            /** Provider Id */
            provider_id: string;
        };
        /** ModelsInfo */
        ModelsInfo: {
            /** Roles */
            roles: string[];
            /** Defaults */
            defaults: {
                [key: string]: components["schemas"]["ModelSpecOut"];
            };
            /** Suggestions */
            suggestions: {
                [key: string]: string[];
            };
        };
        /** ProviderInfo */
        ProviderInfo: {
            /** Id */
            id: string;
            /** Base Url */
            base_url: string;
            /** Token Set */
            token_set: boolean;
        };
        /**
         * Ressources
         * @description Matière première mise à disposition de l'agent (tout optionnel).
         */
        Ressources: {
            /** Urls */
            urls?: string[];
            /** Local Paths */
            local_paths?: string[];
            /** Audio Paths */
            audio_paths?: string[];
            /** Notes */
            notes?: string | null;
        };
        /** RunInfo */
        RunInfo: {
            /** Id */
            id: string;
            /** Channel */
            channel: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Title */
            title?: string | null;
            /** Video */
            video?: string | null;
            /** Gcs Url */
            gcs_url?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Logs
             * @default
             */
            logs: string;
        };
        /** RunRequest */
        RunRequest: {
            /** Channel */
            channel: string;
        };
        /** SkillInfo */
        SkillInfo: {
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VideoItem */
        VideoItem: {
            /** Channel */
            channel: string;
            /** Date */
            date?: string | null;
            /** Name */
            name: string;
            /** Blob */
            blob: string;
            /** Url */
            url: string;
        };
        /** VoicesInfo */
        VoicesInfo: {
            /** Chirp3 */
            chirp3: {
                [key: string]: string[];
            };
            /** Chirp3 Template */
            chirp3_template: string;
            /** Languages */
            languages: string[];
            /** Gemini Voice Model */
            gemini_voice_model: string;
            /** Gemini Note */
            gemini_note: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    catalog_skills_api_catalog_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillInfo"][];
                };
            };
        };
    };
    catalog_voices_api_catalog_voices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoicesInfo"];
                };
            };
        };
    };
    catalog_providers_api_catalog_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderInfo"][];
                };
            };
        };
    };
    catalog_models_api_catalog_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsInfo"];
                };
            };
        };
    };
    list_channels_api_channels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"][];
                };
            };
        };
    };
    create_channel_api_channels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Channel"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_channel_api_channels__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_channel_api_channels__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Channel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_channel_api_channels__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_character_api_characters_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_character_api_characters_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterAsset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    library_api_characters_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterAsset"][];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunInfo"][];
                };
            };
        };
    };
    launch_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gallery_api_gallery_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoItem"][];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
